# ===============================
# Application
# ===============================

base.url=https://www.saucedemo.com/

# ===============================
# Browser
# ===============================

browser=chrome

# ===============================
# Timeouts
# ===============================

implicit.wait=10
explicit.wait=20

# ===============================
# Execution
# ===============================

headless=false

# ===============================
# Window
# ===============================

maximize=true